name: lista_contatos_firebase
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  http: ^0.12.0+2
  mask_text_input_formatter: ^1.1.0
  provider: ^4.0.5
  flushbar: ^1.10.4
  shared_preferences: ^0.5.7+3
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  get_it: ^4.0.4
  brasil_fields: ^0.4.0
  floor: ^0.13.0
  cupertino_icons: ^0.1.3
  sqflite: ^1.3.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.13.0
  build_runner: ^1.10.1
  mobx_codegen: ^1.1.0+1

flutter:
  uses-material-design: true


